---
title: "Figures"
date: "Last knitted on `r format(Sys.Date(), '%d %b %Y')`"
author: "Ciara Asamoto, Sebastian Kopf"
output:
  html_document: 
    df_print: paged # omit to disable paged data table output
    css: stylesheet.css # omit if no need for custom stylesheet
    number_sections: no # change to no for unnumbered sections
    toc: yes # change to no to disable table of contents
    toc_float: true # change to false to keep toc at the top
    toc_depth: 3 # change to specify which headings to include in toc
    code_folding: hide # change to 'show' to show code by default
editor_options:
  chunk_output_type: console # change to inline to show output inline
---

```{r setup, echo = FALSE, message=FALSE, warning=FALSE}
# load libraries
library(tidyverse) 
library(latex2exp)
library(cowplot)
library(broom)
source(file.path("scripts", "plotting_functions.R"))

# global knitting options for automatic saving of all plots as .png and .pdf
knitr::opts_chunk$set(
  eval = FALSE,
  dev = c("png", "pdf"), fig.keep = "all",
  dev.args = list(pdf = list(encoding = "WinAnsi", useDingbats = FALSE)),
  fig.path = file.path("figures", "figure_")
)
```

# Figure

```{r "2_environmental_data", fig.width = 8.5, fig.height = 6}
# load data
marine <-
  readxl::read_excel("data/literature.xlsx", sheet = "marine_data") %>% 
    mutate(type = "marine", info = "marine")
terrestrial <- 
  readxl::read_excel("data/literature.xlsx", sheet = "terrestrial_data") %>% 
    mutate(type = "terrestrial", info = reference)
env_data <- bind_rows(marine, terrestrial) %>% 
  group_by(info) %>% mutate(n_datapoints = n()) %>% ungroup() %>% 
  mutate(
    info = case_when(
      type == "marine" ~ sprintf("combined marine (%d points)\n(from %d publications)", n_datapoints, length(unique(marine$reference))),
      TRUE ~ sprintf("%s (%d points)\n(%s)", environment, n_datapoints, reference) 
    ) %>% factor() %>% fct_inorder()
  )

# slopes
x_range <- c(0, 60)
y_offset <- -1
slope_ribbons <- 
  tibble(
    intercept = y_offset,
    slope = rep(c(1, 0.5), each = 2),
    line = sprintf("%.1f", slope),
    ribbon_width = rep(c(5, 3.5), each = 2),
    x = c(x_range, x_range),
    ymin = intercept + slope * x_range - ribbon_width,
    ymax = intercept + slope * x_range + ribbon_width
  )
slope_lines <- 
  tibble(
    x = 5 + c(x_range * 0.55, x_range * 0.8),
    slope = rep(c(1, 0.5), each = 2),
    line = sprintf("%.1f", slope),
    y = y_offset + slope * x
  )
slope_label <- latex2exp::TeX("$\\frac{^{18}\\epsilon}{^{15}\\epsilon}$ ratio")

# generate plot
p2 <- env_data %>%
  ggplot() +
  # slope ribbons
  geom_ribbon(
    data = slope_ribbons,
    mapping = aes(x = x, ymin = ymin, ymax = ymax, fill = line),
    alpha = 0.2,
    show.legend = TRUE
  ) +
  # slopes
  geom_line(data = slope_lines, mapping = aes(x, y, linetype = line)) +
  # arrows
  geom_line(data = slope_lines,
    mapping = aes(x, y, group = line),
    linetype = 0, arrow = arrow(length = unit(0.03, "npc"), type = "closed")
  ) + 
  # data points
  geom_point(
    data = function(df) filter(df, type == "marine"), 
    mapping = aes(d15N, d18O, color = info, shape = info),
    size = 3, alpha = 0.3
  ) +
  geom_point(
    data = function(df) filter(df, type == "terrestrial"),
    mapping = aes(d15N, d18O, color = info, shape = info),
    size = 3
  ) +
  coord_cartesian(xlim = c(0, 60), ylim = c(0, 40)) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  scale_color_manual(values = c("black", cb_palette[c(7,2:6)]), drop = FALSE) +
  scale_shape_manual(values = c(22, rep(19, 4), rep(17, 2)), drop = FALSE) +
  scale_fill_manual(values = c("black", "grey")) +
  scale_linetype_manual(values = c(2, 1)) +
  theme_figure(text_size = 14) +
  theme(
    legend.text = element_text(margin = margin(t = 3, b = 3))
  ) +
  guides(color=guide_legend(override.aes=list(fill=NA))) +
  # labels
  labs(
    x = latex2exp::TeX("$\\delta^{15}N_{Air}$ of $NO_3^-$"),
    y = latex2exp::TeX("$\\delta^{18}O_{VSMOW}$ of  $NO_3^-$"),
    shape = "datasets", color = "datasets", 
    linetype = slope_label, fill = slope_label
  )

# full plot
p2
```

