#!/bin/bash

# convert RMarkdown files to ipynb
pip install ipyrmd
for f in *.Rmd; do ipyrmd $f; done

# write new README
rm README.md
echo $'# Instructions\n\nExplore this package on binder by modifying the notebooks in RStudio (RMarkdown .Rmd files) or Jupyter Lab (notebook .ipynb files) or by creating a new notebook from scratch.' > README.md

